### PR TITLE
add event_create_listener's spce

### PR DESCRIPTION
**Pull request by JackSie**

### CODE REVIEW

**Comment by rueian** [comment]
少了 on_attachment_created

**Comment by JackSie** [comment]
this is because that the attachment spec which should provide the shared data or the factory hasn't been written.

**Comment by jason1122g** [comment]
你可以先寫 attachment factory

**Comment by JackSie** [comment]
I'm not so familiar with attachment's structure. I think writing the on_attachment_created test after the attachment spec has been done will be a better choice.

**Comment by jason1122g** [comment]
@bdsword

**Comment by rueian** [comment]
那就晚點再 merge

**Comment by JackSie** [comment]
The remaining part has been done.

**Pull request merged**
